export const FETCH_HERO_LIST = "FETCH_HERO_LIST";
export const FETCH_HERO_PROFILE = "FETCH_HERO_PROFILE";
export const UPDATE_CURRENT_HERO_ID = "UPDATE_CURRENT_HERO_ID";
export const UPDATE_HERO_PROFILE = "UPDATE_HERO_PROFILE";
